version: '3'

services:
  web:
    build: .
    #command: /usr/local/bin/entrypoint.sh python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    entrypoint: /app/entrypoint.sh
    restart: always
