# Generated by Django 4.2.5 on 2024-01-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_historicaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
