# Generated by Django 4.2.5 on 2024-02-06 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_connexionapp_desktop_app_and_more'),
        ('accounts', '0004_historicaluser_updated_user_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='departement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='base.departement'),
        ),
    ]
