# Generated by Django 4.2.5 on 2024-01-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_api_apispecification_appdeployment_appserver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Backup_strategie',
            new_name='backup_strategie',
        ),
        migrations.RenameField(
            model_name='historicalapplication',
            old_name='Backup_strategie',
            new_name='backup_strategie',
        ),
    ]
