# Generated by Django 4.2.5 on 2024-01-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_backup_strategie_application_backup_strategie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipadress',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='domainname',
            name='ip_adress',
        ),
        migrations.RemoveField(
            model_name='historicaldomainname',
            name='ip_adress',
        ),
        migrations.DeleteModel(
            name='HistoricalIpAdress',
        ),
        migrations.DeleteModel(
            name='IpAdress',
        ),
    ]
