# Generated by Django 4.2.5 on 2024-01-21 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_remove_ipadress_interface_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('ipv4', models.GenericIPAddressField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.networkinterface')),
            ],
            options={
                'verbose_name': 'Adresse IP',
                'verbose_name_plural': 'Adresses IP',
            },
        ),
        migrations.CreateModel(
            name='HistoricalIpAdress',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('ipv4', models.GenericIPAddressField()),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('interface', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.networkinterface')),
            ],
            options={
                'verbose_name': 'historical Adresse IP',
                'verbose_name_plural': 'historical Adresses IP',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='domainname',
            name='ip_adress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.ipadress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldomainname',
            name='ip_adress',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.ipadress'),
        ),
    ]
