# Generated by Django 4.2.5 on 2024-01-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_ipadress_historicalipadress_domainname_ip_adress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='cluster',
        ),
    ]
