# Generated by Django 4.2.5 on 2024-01-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_server_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='server',
            field=models.ManyToManyField(through='base.DeploiementCluster', to='base.server'),
        ),
    ]
