# Generated by Django 4.2.5 on 2024-01-21 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_cluster_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='ip_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ipadress'),
        ),
        migrations.AddField(
            model_name='historicalcluster',
            name='ip_address',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.ipadress'),
        ),
    ]
