# Generated by Django 4.2.5 on 2024-01-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_cluster_ip_address_historicalcluster_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='server',
            new_name='servers',
        ),
    ]
