# Generated by Django 4.2.5 on 2024-01-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_server_cluster_servers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='module_applicatif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='base.moduleapplicatif'),
        ),
        migrations.AlterField(
            model_name='apidocumentation',
            name='api_specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis_documentations', to='base.apispecification'),
        ),
        migrations.AlterField(
            model_name='apispecification',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis_specifications', to='base.usecase'),
        ),
        migrations.AlterField(
            model_name='appelapi',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_apis', to='base.api'),
        ),
        migrations.AlterField(
            model_name='appelapi',
            name='module_applicatif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_apis', to='base.moduleapplicatif'),
        ),
        migrations.AlterField(
            model_name='appelapi',
            name='use_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_apis', to='base.usecase'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='applications', to='base.apptype'),
        ),
        migrations.AlterField(
            model_name='application',
            name='backup_strategie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='applications', to='base.backupstrategie'),
        ),
        migrations.AlterField(
            model_name='appserver',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps_servers', to='base.server'),
        ),
        migrations.AlterField(
            model_name='architecturediagram',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architectures_diagrams', to='base.process'),
        ),
        migrations.AlterField(
            model_name='callflow',
            name='use_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_flows', to='base.usecase'),
        ),
        migrations.AlterField(
            model_name='database',
            name='db_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='base.databaseserver'),
        ),
        migrations.AlterField(
            model_name='databaseserver',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='databases_servers', to='base.cluster'),
        ),
        migrations.AlterField(
            model_name='databaseserver',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='databases_servers', to='base.server'),
        ),
        migrations.AlterField(
            model_name='datadictionnarymodel',
            name='data_dictionnary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas_dictionnaries_models', to='base.datadictionnary'),
        ),
        migrations.AlterField(
            model_name='datadictionnarymodel',
            name='data_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas_dictionnaries_models', to='base.datamodel'),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas_models', to='base.database'),
        ),
        migrations.AlterField(
            model_name='deploiementcluster',
            name='serveur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='base.server'),
        ),
        migrations.AlterField(
            model_name='domainname',
            name='ip_adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains_names', to='base.ipadress'),
        ),
        migrations.AlterField(
            model_name='ipadress',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='base.networkinterface'),
        ),
        migrations.AlterField(
            model_name='moduleapplicatif',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_applicatifs', to='base.application'),
        ),
        migrations.AlterField(
            model_name='moduleapplicatif',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_applicatifs', to='base.departement'),
        ),
        migrations.AlterField(
            model_name='moduleapplicatif',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='modules_applicatifs', to='base.vendor'),
        ),
        migrations.AlterField(
            model_name='networkinterface',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks_interfaces', to='base.server'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='module_applicatif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='base.moduleapplicatif'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='server_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='base.serverroom'),
        ),
        migrations.AlterField(
            model_name='server',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='base.rack'),
        ),
        migrations.AlterField(
            model_name='serverroom',
            name='datacenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_rooms', to='base.datacenter'),
        ),
        migrations.AlterField(
            model_name='smppaccount',
            name='module_applicatif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smpps_accounts', to='base.moduleapplicatif'),
        ),
        migrations.AlterField(
            model_name='smsshortcode',
            name='smpp_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_short_codes', to='base.smppaccount'),
        ),
        migrations.AlterField(
            model_name='subprocess',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_processes', to='base.process'),
        ),
        migrations.AlterField(
            model_name='technicalrecoveryplan',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicals_recoveries_plans', to='base.application'),
        ),
        migrations.AlterField(
            model_name='url',
            name='domain_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='base.domainname'),
        ),
        migrations.AlterField(
            model_name='url',
            name='module_applicatif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='base.moduleapplicatif'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='sub_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_case', to='base.subprocess'),
        ),
        migrations.AlterField(
            model_name='ussdshortcode',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ussd_short_codes', to='base.url'),
        ),
    ]
