# Generated by Django 4.2.5 on 2024-01-24 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_serverroom_datacenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='sub_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses_cases', to='base.subprocess'),
        ),
    ]
