# Generated by Django 4.2.5 on 2024-01-24 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_usecase_sub_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apispecification',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis_specifications', to='base.api'),
        ),
        migrations.AlterField(
            model_name='historicalapispecification',
            name='api',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.api'),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='sub_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses_case', to='base.subprocess'),
        ),
    ]
