# Generated by Django 4.2.5 on 2024-01-29 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_apispecification_api_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connexionapp',
            name='desktop_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connexions_apps', to='base.desktopapp'),
        ),
        migrations.AlterField(
            model_name='connexionapp',
            name='mobile_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connexions_apps', to='base.mobileapp'),
        ),
        migrations.AlterField(
            model_name='connexionapp',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions_apps', to='base.url'),
        ),
    ]
