# Generated by Django 5.0.3 on 2024-03-15 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_deploiementcluster_cluster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploiementcluster',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploiementClusters', to='base.cluster'),
        ),
        migrations.AlterField(
            model_name='deploiementcluster',
            name='serveur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploiementClusters', to='base.server'),
        ),
    ]
