name: Test and Deploy Django Application

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test
        run: python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: [ 'build_and_test' ]
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Merge main into master on server
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server 'cd /path/to/your/repository && git checkout master && git pull origin master && git merge origin/main && git push origin master'

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server 'cd /path/to/your/application && git pull origin main && python manage.py migrate'
